'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

type WorkerId = 'sol' | 'luna' | 'qwen' | 'deterministic';
type TaskId = 'T-101' | 'T-102' | 'T-103' | 'T-104';
type ReasonCode =
  | 'deterministic_fit'
  | 'speed'
  | 'quality'
  | 'human_judgment';

type Worker = {
  id: WorkerId;
  name: string;
  role: string;
  detail: string;
  tone: string;
  speed: string;
  authority: string;
};

type WorkItem = {
  id: TaskId;
  title: string;
  summary: string;
  recommended: WorkerId;
  owner: WorkerId;
  status: 'queued' | 'staged' | 'approved';
  evidence: string;
  risk: 'low' | 'medium' | 'high';
  acceptance: string[];
};

type RouteScore = {
  worker: WorkerId;
  fit: 'best' | 'viable' | 'avoid';
  rationale: string;
};

type Proposal = {
  taskId: TaskId;
  worker: WorkerId;
  reasonCode: ReasonCode;
  source: 'agent' | 'human';
};

type Activity = {
  id: number;
  source: 'SYSTEM' | 'AGENT' | 'HUMAN';
  text: string;
  time: string;
};

type EvidencePacket = {
  schema_version: 'captain-evidence-packet-v1';
  packet_id: string;
  synthetic_demo: true;
  mission: {
    mission_id: 'MISSION-04';
    title: 'Prepare a verified public release';
    privacy_class: 'public_synthetic_only';
  };
  handoff: {
    task_id: TaskId;
    task_title: string;
    selected_worker: WorkerId;
    worker_role: string;
    reason_code: ReasonCode;
    risk: WorkItem['risk'];
  };
  contract: {
    evidence_method: string;
    acceptance_criteria: string[];
    protected_boundaries: string[];
  };
  authority: {
    route_approved_by: 'human';
    packet_approval_required: true;
    release_executed: false;
  };
};

type VerificationCheck = {
  id: string;
  pass: boolean;
  detail: string;
};

type VerificationReceipt = {
  status: 'pass' | 'fail';
  packet_sha256: string;
  verified_by: 'webmcp_agent' | 'human';
  checks: VerificationCheck[];
};

type PacketState = {
  packet: EvidencePacket;
  packetSha256: string;
  status: 'draft' | 'verified' | 'approved';
  verification: VerificationReceipt | null;
};

const WORKERS: Worker[] = [
  {
    id: 'sol',
    name: 'SOL',
    role: 'Captain',
    detail: 'Architecture, judgment, and final acceptance',
    tone: 'violet',
    speed: 'Deliberate',
    authority: 'Final judgment',
  },
  {
    id: 'luna',
    name: 'LUNA',
    role: 'Builder fleet',
    detail: 'Scoped implementation, tests, and repair',
    tone: 'cyan',
    speed: 'Fast',
    authority: 'Implementation',
  },
  {
    id: 'qwen',
    name: 'QWEN',
    role: 'Resident utility',
    detail: 'Bounded mechanical work with exact checks',
    tone: 'amber',
    speed: 'Warm-local',
    authority: 'Proposal only',
  },
  {
    id: 'deterministic',
    name: 'EXACT',
    role: 'Deterministic tools',
    detail: 'Hashes, schemas, parsers, and reproducible tests',
    tone: 'green',
    speed: 'Immediate',
    authority: 'Objective evidence',
  },
];

const INITIAL_ITEMS: WorkItem[] = [
  {
    id: 'T-101',
    title: 'Normalize configuration schema',
    summary:
      'Convert a synthetic settings object into the published schema without changing protected values.',
    recommended: 'qwen',
    owner: 'qwen',
    status: 'queued',
    evidence: 'Schema validator + exact-value diff',
    risk: 'low',
    acceptance: [
      'All required keys are present',
      'Protected values are unchanged',
      'Validator exits successfully',
    ],
  },
  {
    id: 'T-102',
    title: 'Implement dashboard filters',
    summary:
      'Add accessible queue filters and preserve the shared selected-work-item state.',
    recommended: 'luna',
    owner: 'luna',
    status: 'queued',
    evidence: 'Component tests + keyboard check',
    risk: 'medium',
    acceptance: [
      'All status filters return expected rows',
      'Selection remains visible to the agent',
      'Keyboard navigation passes',
    ],
  },
  {
    id: 'T-103',
    title: 'Review release boundary',
    summary:
      'Decide whether the public package contains only synthetic data and preserves the human release gate.',
    recommended: 'sol',
    owner: 'sol',
    status: 'queued',
    evidence: 'Human decision + boundary checklist',
    risk: 'high',
    acceptance: [
      'No private inputs or identifiers',
      'No hidden external side effects',
      'Human retains release authority',
    ],
  },
  {
    id: 'T-104',
    title: 'Verify package manifest',
    summary:
      'Compare the synthetic release manifest against the files generated by the build.',
    recommended: 'deterministic',
    owner: 'deterministic',
    status: 'queued',
    evidence: 'File inventory + SHA-256 comparison',
    risk: 'low',
    acceptance: [
      'Manifest contains every release file',
      'No ignored file is present',
      'Every recorded hash matches',
    ],
  },
];

const TASK_IDS = INITIAL_ITEMS.map((item) => item.id);
const WORKER_IDS = WORKERS.map((worker) => worker.id);
const REASON_CODES: ReasonCode[] = [
  'deterministic_fit',
  'speed',
  'quality',
  'human_judgment',
];

const workerFor = (workerId: WorkerId) =>
  WORKERS.find((worker) => worker.id === workerId) ?? WORKERS[0];

const isTaskId = (value: unknown): value is TaskId =>
  typeof value === 'string' && TASK_IDS.includes(value as TaskId);

const isWorkerId = (value: unknown): value is WorkerId =>
  typeof value === 'string' && WORKER_IDS.includes(value as WorkerId);

const isReasonCode = (value: unknown): value is ReasonCode =>
  typeof value === 'string' && REASON_CODES.includes(value as ReasonCode);

function routeScores(item: WorkItem): RouteScore[] {
  const defaults: Record<WorkerId, RouteScore> = {
    sol: {
      worker: 'sol',
      fit: 'viable',
      rationale: 'Capable, but reserve expensive judgment for unresolved risk.',
    },
    luna: {
      worker: 'luna',
      fit: 'viable',
      rationale: 'Strong general implementation lane with independent checks.',
    },
    qwen: {
      worker: 'qwen',
      fit: 'avoid',
      rationale: 'Use only for bounded mechanical work with exact validation.',
    },
    deterministic: {
      worker: 'deterministic',
      fit: 'avoid',
      rationale: 'Use only when an exact parser, test, or hash answers the task.',
    },
  };

  defaults[item.recommended] = {
    worker: item.recommended,
    fit: 'best',
    rationale:
      item.recommended === 'sol'
        ? 'The task crosses a release boundary and requires human-backed judgment.'
        : item.recommended === 'luna'
          ? 'The task is non-trivial implementation with clear acceptance tests.'
          : item.recommended === 'qwen'
            ? 'The task is compact, mechanical, proposal-only, and exactly checkable.'
            : 'An exact tool produces the answer without model inference.',
  };

  if (item.recommended === 'deterministic') {
    defaults.qwen.fit = 'viable';
    defaults.qwen.rationale =
      'Useful only to explain a deterministic failure, not to replace the check.';
  }

  if (item.recommended === 'qwen') {
    defaults.deterministic.fit = 'viable';
    defaults.deterministic.rationale =
      'Runs the acceptance check after the resident worker proposes a change.';
  }

  return WORKERS.map((worker) => defaults[worker.id]);
}

function currentTime() {
  return new Intl.DateTimeFormat('en', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(new Date());
}

function buildEvidencePacket(item: WorkItem, approved: Proposal): EvidencePacket {
  return {
    schema_version: 'captain-evidence-packet-v1',
    packet_id: `PKT-${item.id}-${approved.worker.toUpperCase()}`,
    synthetic_demo: true,
    mission: {
      mission_id: 'MISSION-04',
      title: 'Prepare a verified public release',
      privacy_class: 'public_synthetic_only',
    },
    handoff: {
      task_id: item.id,
      task_title: item.title,
      selected_worker: approved.worker,
      worker_role: workerFor(approved.worker).role,
      reason_code: approved.reasonCode,
      risk: item.risk,
    },
    contract: {
      evidence_method: item.evidence,
      acceptance_criteria: [...item.acceptance],
      protected_boundaries: [
        'No private inputs or identifiers',
        'No outbound requests or external side effects',
        'Human approval is required for packet download and release',
      ],
    },
    authority: {
      route_approved_by: 'human',
      packet_approval_required: true,
      release_executed: false,
    },
  };
}

function canonicalPacketJson(packet: EvidencePacket) {
  return `${JSON.stringify(packet, null, 2)}\n`;
}

async function sha256Hex(value: string) {
  const digest = await crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(value),
  );
  return Array.from(new Uint8Array(digest), (byte) =>
    byte.toString(16).padStart(2, '0'),
  ).join('');
}

export default function CaptainConsole() {
  const [items, setItems] = useState<WorkItem[]>(INITIAL_ITEMS);
  const [selectedTaskId, setSelectedTaskId] = useState<TaskId>('T-102');
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const [packetState, setPacketState] = useState<PacketState | null>(null);
  const [toolStatus, setToolStatus] = useState<
    'checking' | 'ready' | 'unavailable' | 'error'
  >('unavailable');
  const [briefingOpen, setBriefingOpen] = useState(false);
  const [activity, setActivity] = useState<Activity[]>([
    {
      id: 1,
      source: 'SYSTEM',
      text: 'Synthetic mission loaded. Release authority remains human-only.',
      time: 'READY',
    },
  ]);
  const itemsRef = useRef(items);
  const packetRef = useRef(packetState);
  const activityId = useRef(1);

  const syncItems = useCallback((nextItems: WorkItem[]) => {
    itemsRef.current = nextItems;
    setItems(nextItems);
  }, []);

  const syncPacketState = useCallback((nextState: PacketState | null) => {
    packetRef.current = nextState;
    setPacketState(nextState);
  }, []);

  useEffect(() => {
    itemsRef.current = items;
  }, [items]);

  useEffect(() => {
    packetRef.current = packetState;
  }, [packetState]);

  const selectedItem = useMemo(
    () => items.find((item) => item.id === selectedTaskId) ?? items[0],
    [items, selectedTaskId],
  );
  const selectedScores = useMemo(
    () => routeScores(selectedItem),
    [selectedItem],
  );

  const addActivity = useCallback(
    (source: Activity['source'], text: string) => {
      activityId.current += 1;
      setActivity((current) => [
        { id: activityId.current, source, text, time: currentTime() },
        ...current,
      ].slice(0, 6));
    },
    [],
  );

  const stageAssignment = useCallback(
    (
      taskId: TaskId,
      worker: WorkerId,
      reasonCode: ReasonCode,
      source: Proposal['source'],
    ) => {
      const item = itemsRef.current.find((candidate) => candidate.id === taskId);
      if (!item) {
        throw new Error('Unknown synthetic work item.');
      }

      setSelectedTaskId(taskId);
      setProposal({ taskId, worker, reasonCode, source });
      syncPacketState(null);
      syncItems(
        itemsRef.current.map((candidate) =>
          candidate.id === taskId
            ? { ...candidate, status: 'staged' }
            : candidate,
        ),
      );
      addActivity(
        source === 'agent' ? 'AGENT' : 'HUMAN',
        `Staged ${taskId} for ${workerFor(worker).name}; approval is still required.`,
      );

      return {
        synthetic_demo: true,
        status: 'staged_for_human_review',
        task_id: taskId,
        proposed_worker: worker,
        reason_code: reasonCode,
        side_effects: 'page_state_only',
        authority: 'No work was executed and no release was approved.',
      };
    },
    [addActivity, syncItems, syncPacketState],
  );

  const verifyCurrentPacket = useCallback(
    async (verifiedBy: VerificationReceipt['verified_by']) => {
      const current = packetRef.current;
      if (!current) {
        return {
          synthetic_demo: true,
          status: 'packet_not_ready',
          side_effects: 'none',
          authority:
            'A human must approve a staged route before a packet can be verified.',
        };
      }

      const sourceItem = INITIAL_ITEMS.find(
        (item) => item.id === current.packet.handoff.task_id,
      );
      const computedHash = await sha256Hex(
        canonicalPacketJson(current.packet),
      );
      const checks: VerificationCheck[] = [
        {
          id: 'schema',
          pass:
            current.packet.schema_version === 'captain-evidence-packet-v1',
          detail: 'Evidence packet schema is recognized.',
        },
        {
          id: 'synthetic-boundary',
          pass:
            current.packet.synthetic_demo === true &&
            current.packet.mission.privacy_class === 'public_synthetic_only',
          detail: 'Packet is explicitly public and synthetic.',
        },
        {
          id: 'task-contract',
          pass:
            Boolean(sourceItem) &&
            sourceItem?.title === current.packet.handoff.task_title &&
            sourceItem?.evidence === current.packet.contract.evidence_method &&
            JSON.stringify(sourceItem?.acceptance) ===
              JSON.stringify(current.packet.contract.acceptance_criteria),
          detail: 'Task, evidence method, and acceptance criteria match.',
        },
        {
          id: 'human-authority',
          pass:
            current.packet.authority.route_approved_by === 'human' &&
            current.packet.authority.packet_approval_required === true &&
            current.packet.authority.release_executed === false,
          detail: 'Human packet approval remains required; release is false.',
        },
        {
          id: 'sha256',
          pass: computedHash === current.packetSha256,
          detail: 'Canonical packet JSON matches its SHA-256 digest.',
        },
      ];
      const pass = checks.every((check) => check.pass);
      const receipt: VerificationReceipt = {
        status: pass ? 'pass' : 'fail',
        packet_sha256: computedHash,
        verified_by: verifiedBy,
        checks,
      };

      if (packetRef.current !== current) {
        return {
          synthetic_demo: true,
          status: 'packet_changed',
          packet_id: current.packet.packet_id,
          side_effects: 'none',
          authority:
            'The packet changed during verification; a fresh verification is required.',
        };
      }

      const nextPacketState: PacketState = {
        ...current,
        status: pass
          ? current.status === 'approved'
            ? 'approved'
            : 'verified'
          : 'draft',
        verification: receipt,
      };
      syncPacketState(nextPacketState);
      addActivity(
        verifiedBy === 'webmcp_agent' ? 'AGENT' : 'HUMAN',
        pass
          ? `Verified ${current.packet.packet_id}; packet approval is still human-only.`
          : `Verification failed for ${current.packet.packet_id}.`,
      );

      return {
        synthetic_demo: true,
        status: pass
          ? current.status === 'approved'
            ? 'verified_approval_preserved'
            : 'verified_for_human_review'
          : 'verification_failed',
        packet_id: current.packet.packet_id,
        packet_sha256: computedHash,
        verified_by: verifiedBy,
        checks,
        side_effects: 'verification_receipt_only',
        authority:
          'The agent verifies the packet; packet approval and download remain human-only.',
      };
    },
    [addActivity, syncPacketState],
  );

  useEffect(() => {
    const modelContext = document.modelContext;
    if (!modelContext?.registerTool) {
      return;
    }

    const registration = new AbortController();

    const register = async () => {
      try {
        const taskEnum = [...TASK_IDS];
        const workerEnum = [...WORKER_IDS];
        const reasonEnum = [...REASON_CODES];

        await modelContext.registerTool(
          {
            name: 'get_mission_brief',
            title: 'Get mission brief',
            description:
              'Read the current synthetic mission, work queue, evidence gates, and human authority boundary.',
            inputSchema: {
              type: 'object',
              properties: {},
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (_input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              return {
                synthetic_demo: true,
                mission: 'Prepare a verified public release',
                health: 'ready',
                work_items: itemsRef.current.map((item) => ({
                  id: item.id,
                  title: item.title,
                  status: item.status,
                  current_owner: item.owner,
                  recommended_worker: item.recommended,
                  risk: item.risk,
                  evidence: item.evidence,
                })),
                privacy: 'public_synthetic_only',
                evidence_packet: packetRef.current
                  ? {
                      packet_id: packetRef.current.packet.packet_id,
                      status: packetRef.current.status,
                      packet_sha256: packetRef.current.packetSha256,
                    }
                  : { status: 'not_created' },
                authority:
                  'Agents may inspect, stage, and verify. A human must approve assignments, packets, and releases.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'inspect_work_item',
            title: 'Inspect work item',
            description:
              'Read one synthetic work item, including its risk, acceptance criteria, and recommended worker.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
              },
              required: ['task_id'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              const item = itemsRef.current.find(
                (candidate) => candidate.id === input.task_id,
              );
              if (!item) throw new Error('Work item not found.');
              return {
                synthetic_demo: true,
                ...item,
                authority:
                  'Inspection does not execute work or change release state.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'compare_worker_routes',
            title: 'Compare worker routes',
            description:
              'Compare Sol, Luna, Qwen, and deterministic-tool fit for one synthetic work item.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
              },
              required: ['task_id'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              const item = itemsRef.current.find(
                (candidate) => candidate.id === input.task_id,
              );
              if (!item) throw new Error('Work item not found.');
              return {
                synthetic_demo: true,
                task_id: item.id,
                recommended_worker: item.recommended,
                routes: routeScores(item),
                policy:
                  'Prefer exact tools first, then the smallest sufficient worker; Sol retains final judgment.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'focus_work_item',
            title: 'Focus work item',
            description:
              'Focus one synthetic work item in the shared interface so the person and agent inspect the same state.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
              },
              required: ['task_id'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: false, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              setSelectedTaskId(input.task_id);
              addActivity('AGENT', `Focused ${input.task_id} in the shared view.`);
              return {
                synthetic_demo: true,
                status: 'focused_in_page',
                task_id: input.task_id,
                side_effects: 'selection_only',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'stage_assignment',
            title: 'Stage assignment',
            description:
              'Stage a reversible worker proposal in the shared synthetic page. This never executes work, approves a release, or contacts an external service.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
                worker: {
                  type: 'string',
                  enum: workerEnum,
                  description: 'Worker proposed for this synthetic item.',
                },
                reason_code: {
                  type: 'string',
                  enum: reasonEnum,
                  description: 'Bounded reason for the proposal.',
                },
              },
              required: ['task_id', 'worker', 'reason_code'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: false, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              if (!isWorkerId(input.worker)) throw new Error('Invalid worker.');
              if (!isReasonCode(input.reason_code)) {
                throw new Error('Invalid reason_code.');
              }
              return stageAssignment(
                input.task_id,
                input.worker,
                input.reason_code,
                'agent',
              );
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'inspect_evidence_packet',
            title: 'Inspect evidence packet',
            description:
              'Read the current synthetic handoff contract, acceptance criteria, authority boundary, and SHA-256 digest after a human approves the route.',
            inputSchema: {
              type: 'object',
              properties: {},
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (_input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              const current = packetRef.current;
              if (!current) {
                return {
                  synthetic_demo: true,
                  status: 'packet_not_ready',
                  authority:
                    'A human must approve a staged route before a packet exists.',
                };
              }
              return {
                synthetic_demo: true,
                status: current.status,
                packet: current.packet,
                packet_sha256: current.packetSha256,
                verification: current.verification,
                authority:
                  'Inspection does not approve, download, publish, or release the packet.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'verify_evidence_packet',
            title: 'Verify evidence packet',
            description:
              'Recompute the current synthetic packet digest, compare its task contract, and record a visible verification receipt. This never approves or downloads the packet.',
            inputSchema: {
              type: 'object',
              properties: {},
              additionalProperties: false,
            },
            annotations: { readOnlyHint: false, untrustedContentHint: false },
            execute: async (_input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              const result = await verifyCurrentPacket('webmcp_agent');
              return {
                ...result,
                verified_by: 'webmcp_agent',
              };
            },
          },
          { signal: registration.signal },
        );

        setToolStatus('ready');
        addActivity('SYSTEM', 'Seven WebMCP site tools registered for this page.');
      } catch (error) {
        if (!registration.signal.aborted) {
          console.error('WebMCP registration failed', error);
          setToolStatus('error');
        }
      }
    };

    void register();
    return () => registration.abort();
  }, [addActivity, stageAssignment, verifyCurrentPacket]);

  const approveProposal = async () => {
    if (!proposal) return;
    const approved = proposal;
    const sourceItem = itemsRef.current.find(
      (item) => item.id === approved.taskId,
    );
    if (!sourceItem) return;

    syncItems(
      itemsRef.current.map((item) =>
        item.id === approved.taskId
          ? { ...item, owner: approved.worker, status: 'approved' }
          : item,
      ),
    );
    const packet = buildEvidencePacket(sourceItem, approved);
    const packetSha256 = await sha256Hex(canonicalPacketJson(packet));
    const nextPacketState: PacketState = {
      packet,
      packetSha256,
      status: 'draft',
      verification: null,
    };
    syncPacketState(nextPacketState);
    addActivity(
      'HUMAN',
      `Approved ${approved.taskId} route and generated ${packet.packet_id}.`,
    );
    setProposal(null);
  };

  const rejectProposal = () => {
    if (!proposal) return;
    syncItems(
      itemsRef.current.map((item) =>
        item.id === proposal.taskId ? { ...item, status: 'queued' } : item,
      ),
    );
    addActivity('HUMAN', `Returned ${proposal.taskId} to the queue.`);
    setProposal(null);
    syncPacketState(null);
  };

  const approvePacket = async () => {
    const current = packetRef.current;
    if (
      !current ||
      current.status !== 'verified' ||
      current.verification?.status !== 'pass' ||
      current.verification.packet_sha256 !== current.packetSha256
    ) {
      return;
    }

    const computedHash = await sha256Hex(
      canonicalPacketJson(current.packet),
    );
    if (
      packetRef.current !== current ||
      computedHash !== current.packetSha256 ||
      current.verification.packet_sha256 !== computedHash
    ) {
      if (packetRef.current === current) {
        syncPacketState({ ...current, status: 'draft', verification: null });
      }
      addActivity(
        'SYSTEM',
        `Blocked ${current.packet.packet_id} approval because packet integrity changed.`,
      );
      return;
    }

    const nextPacketState: PacketState = { ...current, status: 'approved' };
    syncPacketState(nextPacketState);
    addActivity(
      'HUMAN',
      `Approved ${current.packet.packet_id} for local download. Release remains false.`,
    );
  };

  const downloadEvidencePacket = async () => {
    const current = packetRef.current;
    if (
      !current ||
      current.status !== 'approved' ||
      current.verification?.status !== 'pass' ||
      current.verification.packet_sha256 !== current.packetSha256
    ) {
      return;
    }

    const computedHash = await sha256Hex(
      canonicalPacketJson(current.packet),
    );
    if (
      packetRef.current !== current ||
      computedHash !== current.packetSha256 ||
      current.verification.packet_sha256 !== computedHash
    ) {
      if (packetRef.current === current) {
        syncPacketState({ ...current, status: 'draft', verification: null });
      }
      addActivity(
        'SYSTEM',
        `Blocked ${current.packet.packet_id} download because packet integrity changed.`,
      );
      return;
    }

    const envelope = {
      envelope_version: 'captain-evidence-envelope-v1',
      packet_sha256: computedHash,
      verification: current.verification,
      human_approval: {
        status: 'approved',
        authority: 'human_only',
      },
      release: { executed: false },
      packet: current.packet,
    };
    const downloadJson = `${JSON.stringify(envelope, null, 2)}\n`;
    const blob = new Blob([downloadJson], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${current.packet.packet_id.toLowerCase()}-evidence.json`;
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
    addActivity(
      'HUMAN',
      `Downloaded ${current.packet.packet_id}; no release was executed.`,
    );
  };

  const stageRecommended = () => {
    stageAssignment(
      selectedItem.id,
      selectedItem.recommended,
      selectedItem.recommended === 'deterministic'
        ? 'deterministic_fit'
        : selectedItem.recommended === 'sol'
          ? 'human_judgment'
          : selectedItem.recommended === 'luna'
            ? 'quality'
            : 'speed',
      'human',
    );
  };

  const statusLabel = {
    checking: 'CHECKING SITE TOOLS',
    ready: '7 SITE TOOLS READY',
    unavailable: 'UI READY · WEBMCP NOT DETECTED',
    error: 'SITE TOOL REGISTRATION ERROR',
  }[toolStatus];

  return (
    <main className="shell">
      <header className="topbar">
        <a className="brand" href="#top" aria-label="Captain home">
          <span className="brandMark">C</span>
          <span>
            <strong>CAPTAIN</strong>
            <small>Human-agent operations</small>
          </span>
        </a>
        <button
          className={`toolSignal ${toolStatus}`}
          type="button"
          onClick={() => setBriefingOpen((open) => !open)}
          aria-expanded={briefingOpen}
          aria-controls="agent-briefing"
        >
          <span className="pulse" />
          {statusLabel}
        </button>
      </header>

      <section className="hero" id="top">
        <div>
          <p className="eyebrow">SHARED CONTROL ROOM / SYNTHETIC DEMO</p>
          <h1>One manager. The right worker. Every decision visible.</h1>
          <p className="lede">
            Captain turns a mixed AI fleet into a legible team. The agent can
            inspect, compare, stage, and verify a real evidence packet while
            the human keeps approval, download, and release authority.
          </p>
          <div className="heroActions">
            <button
              className="primaryButton compact"
              type="button"
              onClick={() => {
                setBriefingOpen(true);
                document
                  .getElementById('agent-briefing')
                  ?.scrollIntoView({ behavior: 'smooth', block: 'center' });
              }}
            >
              Try the agent briefing
            </button>
            <a className="textLink" href="#why-webmcp">
              Why WebMCP <span aria-hidden="true">↘</span>
            </a>
          </div>
        </div>
        <div className="heroStat" aria-label="Current mission health">
          <span>MISSION HEALTH</span>
          <strong>READY</strong>
          <small>7 semantic tools · 0 private inputs</small>
          <div className="healthLine">
            <i />
            <i />
            <i />
            <i />
          </div>
        </div>
      </section>

      <section className="workspace" aria-label="Captain operations workspace">
        <article className="panel missionPanel">
          <div className="panelHead">
            <div>
              <p className="sectionLabel">MISSION 04</p>
              <h2>Prepare a verified public release</h2>
            </div>
            <span className="statusPill">IN REVIEW</span>
          </div>

          <div className="workerRail">
            {WORKERS.slice(0, 3).map((worker) => (
              <div className={`workerCard ${worker.tone}`} key={worker.id}>
                <span>{worker.name}</span>
                <strong>{worker.role}</strong>
                <small>{worker.detail}</small>
              </div>
            ))}
          </div>

          <div className="queueHead">
            <h3>Work queue</h3>
            <span>{items.filter((item) => item.status !== 'approved').length} open items</span>
          </div>
          <div className="queueList">
            {items.map((item, index) => (
              <button
                className={`queueItem ${
                  item.id === selectedTaskId ? 'selected' : ''
                }`}
                key={item.id}
                type="button"
                onClick={() => {
                  setSelectedTaskId(item.id);
                  addActivity('HUMAN', `Focused ${item.id} in the shared view.`);
                }}
                aria-pressed={item.id === selectedTaskId}
              >
                <span className="queueIndex">0{index + 1}</span>
                <span className="queueTitle">
                  <strong>{item.title}</strong>
                  <small>{item.evidence}</small>
                </span>
                <span className={`owner owner-${item.owner}`}>
                  {workerFor(item.owner).name}
                </span>
                <span className={`queueStatus ${item.status}`}>{item.status}</span>
              </button>
            ))}
          </div>
        </article>

        <aside className="panel agentPanel">
          <div className="panelHead compactHead">
            <p className="sectionLabel">SHARED INSPECTOR</p>
            <span className={`risk risk-${selectedItem.risk}`}>
              {selectedItem.risk} risk
            </span>
          </div>
          <h2>{selectedItem.id}</h2>
          <h3>{selectedItem.title}</h3>
          <p>{selectedItem.summary}</p>

          <div className="recommendation">
            <span>RECOMMENDED ROUTE</span>
            <strong>{workerFor(selectedItem.recommended).name}</strong>
            <small>{workerFor(selectedItem.recommended).detail}</small>
          </div>

          <div className="acceptanceList">
            {selectedItem.acceptance.map((criterion) => (
              <div key={criterion}>
                <span aria-hidden="true">✓</span>
                {criterion}
              </div>
            ))}
          </div>

          <button
            className="primaryButton"
            type="button"
            onClick={stageRecommended}
          >
            Stage recommended assignment
          </button>
          <small className="buttonNote">Proposal only · human approval required</small>
        </aside>
      </section>

      {proposal && (
        <section className="proposalBar" aria-live="polite">
          <div>
            <span>STAGED PROPOSAL</span>
            <strong>
              {proposal.taskId} → {workerFor(proposal.worker).name}
            </strong>
            <small>
              Source: {proposal.source} · Reason: {proposal.reasonCode.replaceAll('_', ' ')}
            </small>
          </div>
          <div className="proposalActions">
            <button type="button" className="ghostButton" onClick={rejectProposal}>
              Return
            </button>
            <button type="button" className="approveButton" onClick={approveProposal}>
              Human approve route
            </button>
          </div>
        </section>
      )}

      <section className="evidencePacket panel" id="evidence-packet" aria-live="polite">
        <div className="packetIntro">
          <div className="panelHead compactHead">
            <p className="sectionLabel">EVIDENCE PACKET</p>
            <span className={`packetStatus ${packetState?.status ?? 'locked'}`}>
              {packetState?.status ?? 'locked'}
            </span>
          </div>
          <h2>A routing decision becomes proof.</h2>
          <p>
            Route approval creates a stable handoff contract. The agent verifies
            the packet against the original task and SHA-256 digest. Packet
            approval and download remain human-only.
          </p>

          {packetState ? (
            <div className="packetContract">
              <div>
                <span>PACKET</span>
                <strong>{packetState.packet.packet_id}</strong>
              </div>
              <div>
                <span>HANDOFF</span>
                <strong>
                  {packetState.packet.handoff.task_id} →{' '}
                  {workerFor(packetState.packet.handoff.selected_worker).name}
                </strong>
              </div>
              <div>
                <span>EVIDENCE</span>
                <strong>{packetState.packet.contract.evidence_method}</strong>
              </div>
            </div>
          ) : (
            <div className="packetEmpty">
              <span>01</span>
              <p>Stage a route and use <b>Human approve route</b> to create the packet.</p>
            </div>
          )}
        </div>

        <div className="packetVerification">
          <span className="verificationLabel">DETERMINISTIC RECEIPT</span>
          {!packetState ? (
            <>
              <strong>Waiting for route approval</strong>
              <p>No packet exists yet. The agent cannot invent one.</p>
            </>
          ) : (
            <>
              <strong>
                {packetState.status === 'draft'
                  ? 'Waiting for agent verification'
                  : packetState.status === 'verified'
                    ? 'All contract checks passed'
                    : 'Human-approved download ready'}
              </strong>
              <code title={packetState.packetSha256}>
                SHA-256 {packetState.packetSha256.slice(0, 16)}…
              </code>
              <div className="verificationChecks">
                {(packetState.verification?.checks ?? [
                  { id: 'schema', pass: false, detail: 'Schema and synthetic boundary' },
                  { id: 'contract', pass: false, detail: 'Task and acceptance contract' },
                  { id: 'authority', pass: false, detail: 'Human authority and digest' },
                ]).map((check) => (
                  <span className={check.pass ? 'pass' : 'pending'} key={check.id}>
                    {check.pass ? '✓' : '○'} {check.detail}
                  </span>
                ))}
              </div>
              <div className="packetActions">
                {packetState.status === 'draft' && (
                  <button
                    type="button"
                    className="ghostButton"
                    onClick={() => void verifyCurrentPacket('human')}
                  >
                    Verify locally
                  </button>
                )}
                {packetState.status === 'verified' && (
                  <button
                    type="button"
                    className="approveButton"
                    onClick={() => void approvePacket()}
                  >
                    Human approve packet
                  </button>
                )}
                {packetState.status === 'approved' && (
                  <button
                    type="button"
                    className="downloadButton"
                    onClick={() => void downloadEvidencePacket()}
                  >
                    Download JSON evidence packet
                  </button>
                )}
              </div>
            </>
          )}
        </div>
      </section>

      <section
        className={`briefing panel ${briefingOpen ? 'open' : ''}`}
        id="agent-briefing"
        aria-hidden={!briefingOpen}
      >
        <div>
          <p className="sectionLabel">DEMO BRIEFING</p>
          <h2>Give the agent a goal, not a click path.</h2>
          <p>
            Open this page in ChatGPT&apos;s built-in browser and use the prompt
            below. The agent can inspect live state through the registered site
            tools, focus the same work item you see, compare routes, and stage a
            reversible proposal. After you approve the route, the agent verifies
            the packet and leaves final approval to you.
          </p>
        </div>
        <div className="promptCard">
          <span>SUGGESTED PROMPT</span>
          <p>
            Inspect the mission, compare routes for T-102, focus it in the shared
            interface, then stage the safest assignment. After I approve the
            route, inspect and verify the evidence packet. Do not approve,
            download, publish, or release anything.
          </p>
        </div>
      </section>

      <section className="routeSection">
        <div className="sectionIntro">
          <p className="sectionLabel">ROUTE COMPARISON</p>
          <h2>The reasoning stays inspectable.</h2>
          <p>
            The page and the WebMCP tool call the same routing function. What the
            agent reads is exactly what the person sees.
          </p>
        </div>
        <div className="routeGrid">
          {selectedScores.map((score) => {
            const worker = workerFor(score.worker);
            return (
              <article className={`routeCard ${score.fit}`} key={score.worker}>
                <div>
                  <span>{worker.name}</span>
                  <b>{score.fit}</b>
                </div>
                <strong>{worker.role}</strong>
                <p>{score.rationale}</p>
                <small>
                  {worker.speed} · {worker.authority}
                </small>
              </article>
            );
          })}
        </div>
      </section>

      <section className="whySection" id="why-webmcp">
        <div className="sectionIntro">
          <p className="sectionLabel">WHY WEBMCP</p>
          <h2>Shared state beats screen guessing.</h2>
        </div>
        <div className="benefitGrid">
          <article>
            <span>01</span>
            <h3>Narrow tools</h3>
            <p>Enums and bounded schemas replace vague pointer-and-click automation.</p>
          </article>
          <article>
            <span>02</span>
            <h3>Visible changes</h3>
            <p>Agent actions update the same page the person is already reviewing.</p>
          </article>
          <article>
            <span>03</span>
            <h3>Human authority</h3>
            <p>Agents stage proposals; approval and release remain explicit human actions.</p>
          </article>
          <article>
            <span>04</span>
            <h3>Verifiable output</h3>
            <p>A stable packet and digest turn an opaque handoff into portable evidence.</p>
          </article>
        </div>
      </section>

      <section className="activitySection panel" aria-live="polite">
        <div className="activityHead">
          <div>
            <p className="sectionLabel">RECENT ACTIVITY</p>
            <h2>Every handoff leaves a trace.</h2>
          </div>
          <span>SESSION ONLY · NO TELEMETRY</span>
        </div>
        <div className="activityList">
          {activity.map((entry) => (
            <div key={entry.id}>
              <span className={`activitySource source-${entry.source.toLowerCase()}`}>
                {entry.source}
              </span>
              <p>{entry.text}</p>
              <time>{entry.time}</time>
            </div>
          ))}
        </div>
      </section>

      <footer>
        <span>PUBLIC SYNTHETIC DATA</span>
        <span>HUMAN RELEASE GATE</span>
        <span>7 IMPERATIVE WEBMCP TOOLS</span>
        <span>WEBMCP DRAFT · 2026</span>
      </footer>
    </main>
  );
}
