'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

type WorkerId = 'sol' | 'luna' | 'qwen' | 'deterministic';
type TaskId = 'T-101' | 'T-102' | 'T-103' | 'T-104';
type ReasonCode =
  | 'deterministic_fit'
  | 'speed'
  | 'quality'
  | 'human_judgment';

type Worker = {
  id: WorkerId;
  name: string;
  role: string;
  detail: string;
  tone: string;
  speed: string;
  authority: string;
};

type WorkItem = {
  id: TaskId;
  title: string;
  summary: string;
  recommended: WorkerId;
  owner: WorkerId;
  status: 'queued' | 'staged' | 'approved';
  evidence: string;
  risk: 'low' | 'medium' | 'high';
  acceptance: string[];
};

type RouteScore = {
  worker: WorkerId;
  fit: 'best' | 'viable' | 'avoid';
  rationale: string;
};

type Proposal = {
  taskId: TaskId;
  worker: WorkerId;
  reasonCode: ReasonCode;
  source: 'agent' | 'human';
};

type Activity = {
  id: number;
  source: 'SYSTEM' | 'AGENT' | 'HUMAN';
  text: string;
  time: string;
};

const WORKERS: Worker[] = [
  {
    id: 'sol',
    name: 'SOL',
    role: 'Captain',
    detail: 'Architecture, judgment, and final acceptance',
    tone: 'violet',
    speed: 'Deliberate',
    authority: 'Final judgment',
  },
  {
    id: 'luna',
    name: 'LUNA',
    role: 'Builder fleet',
    detail: 'Scoped implementation, tests, and repair',
    tone: 'cyan',
    speed: 'Fast',
    authority: 'Implementation',
  },
  {
    id: 'qwen',
    name: 'QWEN',
    role: 'Resident utility',
    detail: 'Bounded mechanical work with exact checks',
    tone: 'amber',
    speed: 'Warm-local',
    authority: 'Proposal only',
  },
  {
    id: 'deterministic',
    name: 'EXACT',
    role: 'Deterministic tools',
    detail: 'Hashes, schemas, parsers, and reproducible tests',
    tone: 'green',
    speed: 'Immediate',
    authority: 'Objective evidence',
  },
];

const INITIAL_ITEMS: WorkItem[] = [
  {
    id: 'T-101',
    title: 'Normalize configuration schema',
    summary:
      'Convert a synthetic settings object into the published schema without changing protected values.',
    recommended: 'qwen',
    owner: 'qwen',
    status: 'queued',
    evidence: 'Schema validator + exact-value diff',
    risk: 'low',
    acceptance: [
      'All required keys are present',
      'Protected values are unchanged',
      'Validator exits successfully',
    ],
  },
  {
    id: 'T-102',
    title: 'Implement dashboard filters',
    summary:
      'Add accessible queue filters and preserve the shared selected-work-item state.',
    recommended: 'luna',
    owner: 'luna',
    status: 'queued',
    evidence: 'Component tests + keyboard check',
    risk: 'medium',
    acceptance: [
      'All status filters return expected rows',
      'Selection remains visible to the agent',
      'Keyboard navigation passes',
    ],
  },
  {
    id: 'T-103',
    title: 'Review release boundary',
    summary:
      'Decide whether the public package contains only synthetic data and preserves the human release gate.',
    recommended: 'sol',
    owner: 'sol',
    status: 'queued',
    evidence: 'Human decision + boundary checklist',
    risk: 'high',
    acceptance: [
      'No private inputs or identifiers',
      'No hidden external side effects',
      'Human retains release authority',
    ],
  },
  {
    id: 'T-104',
    title: 'Verify package manifest',
    summary:
      'Compare the synthetic release manifest against the files generated by the build.',
    recommended: 'deterministic',
    owner: 'deterministic',
    status: 'queued',
    evidence: 'File inventory + SHA-256 comparison',
    risk: 'low',
    acceptance: [
      'Manifest contains every release file',
      'No ignored file is present',
      'Every recorded hash matches',
    ],
  },
];

const TASK_IDS = INITIAL_ITEMS.map((item) => item.id);
const WORKER_IDS = WORKERS.map((worker) => worker.id);
const REASON_CODES: ReasonCode[] = [
  'deterministic_fit',
  'speed',
  'quality',
  'human_judgment',
];

const workerFor = (workerId: WorkerId) =>
  WORKERS.find((worker) => worker.id === workerId) ?? WORKERS[0];

const isTaskId = (value: unknown): value is TaskId =>
  typeof value === 'string' && TASK_IDS.includes(value as TaskId);

const isWorkerId = (value: unknown): value is WorkerId =>
  typeof value === 'string' && WORKER_IDS.includes(value as WorkerId);

const isReasonCode = (value: unknown): value is ReasonCode =>
  typeof value === 'string' && REASON_CODES.includes(value as ReasonCode);

function routeScores(item: WorkItem): RouteScore[] {
  const defaults: Record<WorkerId, RouteScore> = {
    sol: {
      worker: 'sol',
      fit: 'viable',
      rationale: 'Capable, but reserve expensive judgment for unresolved risk.',
    },
    luna: {
      worker: 'luna',
      fit: 'viable',
      rationale: 'Strong general implementation lane with independent checks.',
    },
    qwen: {
      worker: 'qwen',
      fit: 'avoid',
      rationale: 'Use only for bounded mechanical work with exact validation.',
    },
    deterministic: {
      worker: 'deterministic',
      fit: 'avoid',
      rationale: 'Use only when an exact parser, test, or hash answers the task.',
    },
  };

  defaults[item.recommended] = {
    worker: item.recommended,
    fit: 'best',
    rationale:
      item.recommended === 'sol'
        ? 'The task crosses a release boundary and requires human-backed judgment.'
        : item.recommended === 'luna'
          ? 'The task is non-trivial implementation with clear acceptance tests.'
          : item.recommended === 'qwen'
            ? 'The task is compact, mechanical, proposal-only, and exactly checkable.'
            : 'An exact tool produces the answer without model inference.',
  };

  if (item.recommended === 'deterministic') {
    defaults.qwen.fit = 'viable';
    defaults.qwen.rationale =
      'Useful only to explain a deterministic failure, not to replace the check.';
  }

  if (item.recommended === 'qwen') {
    defaults.deterministic.fit = 'viable';
    defaults.deterministic.rationale =
      'Runs the acceptance check after the resident worker proposes a change.';
  }

  return WORKERS.map((worker) => defaults[worker.id]);
}

function currentTime() {
  return new Intl.DateTimeFormat('en', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(new Date());
}

export default function CaptainConsole() {
  const [items, setItems] = useState<WorkItem[]>(INITIAL_ITEMS);
  const [selectedTaskId, setSelectedTaskId] = useState<TaskId>('T-102');
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const [toolStatus, setToolStatus] = useState<
    'checking' | 'ready' | 'unavailable' | 'error'
  >('unavailable');
  const [briefingOpen, setBriefingOpen] = useState(false);
  const [activity, setActivity] = useState<Activity[]>([
    {
      id: 1,
      source: 'SYSTEM',
      text: 'Synthetic mission loaded. Release authority remains human-only.',
      time: 'READY',
    },
  ]);
  const itemsRef = useRef(items);
  const activityId = useRef(1);

  useEffect(() => {
    itemsRef.current = items;
  }, [items]);

  const selectedItem = useMemo(
    () => items.find((item) => item.id === selectedTaskId) ?? items[0],
    [items, selectedTaskId],
  );
  const selectedScores = useMemo(
    () => routeScores(selectedItem),
    [selectedItem],
  );

  const addActivity = useCallback(
    (source: Activity['source'], text: string) => {
      activityId.current += 1;
      setActivity((current) => [
        { id: activityId.current, source, text, time: currentTime() },
        ...current,
      ].slice(0, 6));
    },
    [],
  );

  const stageAssignment = useCallback(
    (
      taskId: TaskId,
      worker: WorkerId,
      reasonCode: ReasonCode,
      source: Proposal['source'],
    ) => {
      const item = itemsRef.current.find((candidate) => candidate.id === taskId);
      if (!item) {
        throw new Error('Unknown synthetic work item.');
      }

      setSelectedTaskId(taskId);
      setProposal({ taskId, worker, reasonCode, source });
      setItems((current) =>
        current.map((candidate) =>
          candidate.id === taskId
            ? { ...candidate, status: 'staged' }
            : candidate,
        ),
      );
      addActivity(
        source === 'agent' ? 'AGENT' : 'HUMAN',
        `Staged ${taskId} for ${workerFor(worker).name}; approval is still required.`,
      );

      return {
        synthetic_demo: true,
        status: 'staged_for_human_review',
        task_id: taskId,
        proposed_worker: worker,
        reason_code: reasonCode,
        side_effects: 'page_state_only',
        authority: 'No work was executed and no release was approved.',
      };
    },
    [addActivity],
  );

  useEffect(() => {
    const modelContext = document.modelContext;
    if (!modelContext?.registerTool) {
      return;
    }

    const registration = new AbortController();

    const register = async () => {
      try {
        const taskEnum = [...TASK_IDS];
        const workerEnum = [...WORKER_IDS];
        const reasonEnum = [...REASON_CODES];

        await modelContext.registerTool(
          {
            name: 'get_mission_brief',
            title: 'Get mission brief',
            description:
              'Read the current synthetic mission, work queue, evidence gates, and human authority boundary.',
            inputSchema: {
              type: 'object',
              properties: {},
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (_input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              return {
                synthetic_demo: true,
                mission: 'Prepare a verified public release',
                health: 'ready',
                work_items: itemsRef.current.map((item) => ({
                  id: item.id,
                  title: item.title,
                  status: item.status,
                  current_owner: item.owner,
                  recommended_worker: item.recommended,
                  risk: item.risk,
                  evidence: item.evidence,
                })),
                privacy: 'public_synthetic_only',
                authority:
                  'Agents may inspect and stage proposals. A human must approve assignments and releases.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'inspect_work_item',
            title: 'Inspect work item',
            description:
              'Read one synthetic work item, including its risk, acceptance criteria, and recommended worker.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
              },
              required: ['task_id'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              const item = itemsRef.current.find(
                (candidate) => candidate.id === input.task_id,
              );
              if (!item) throw new Error('Work item not found.');
              return {
                synthetic_demo: true,
                ...item,
                authority:
                  'Inspection does not execute work or change release state.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'compare_worker_routes',
            title: 'Compare worker routes',
            description:
              'Compare Sol, Luna, Qwen, and deterministic-tool fit for one synthetic work item.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
              },
              required: ['task_id'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: true, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              const item = itemsRef.current.find(
                (candidate) => candidate.id === input.task_id,
              );
              if (!item) throw new Error('Work item not found.');
              return {
                synthetic_demo: true,
                task_id: item.id,
                recommended_worker: item.recommended,
                routes: routeScores(item),
                policy:
                  'Prefer exact tools first, then the smallest sufficient worker; Sol retains final judgment.',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'focus_work_item',
            title: 'Focus work item',
            description:
              'Focus one synthetic work item in the shared interface so the person and agent inspect the same state.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
              },
              required: ['task_id'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: false, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              setSelectedTaskId(input.task_id);
              addActivity('AGENT', `Focused ${input.task_id} in the shared view.`);
              return {
                synthetic_demo: true,
                status: 'focused_in_page',
                task_id: input.task_id,
                side_effects: 'selection_only',
              };
            },
          },
          { signal: registration.signal },
        );

        await modelContext.registerTool(
          {
            name: 'stage_assignment',
            title: 'Stage assignment',
            description:
              'Stage a reversible worker proposal in the shared synthetic page. This never executes work, approves a release, or contacts an external service.',
            inputSchema: {
              type: 'object',
              properties: {
                task_id: {
                  type: 'string',
                  enum: taskEnum,
                  description: 'Exact synthetic work item identifier.',
                },
                worker: {
                  type: 'string',
                  enum: workerEnum,
                  description: 'Worker proposed for this synthetic item.',
                },
                reason_code: {
                  type: 'string',
                  enum: reasonEnum,
                  description: 'Bounded reason for the proposal.',
                },
              },
              required: ['task_id', 'worker', 'reason_code'],
              additionalProperties: false,
            },
            annotations: { readOnlyHint: false, untrustedContentHint: false },
            execute: async (input, options) => {
              if (options?.signal?.aborted) throw options.signal.reason;
              if (!isTaskId(input.task_id)) throw new Error('Invalid task_id.');
              if (!isWorkerId(input.worker)) throw new Error('Invalid worker.');
              if (!isReasonCode(input.reason_code)) {
                throw new Error('Invalid reason_code.');
              }
              return stageAssignment(
                input.task_id,
                input.worker,
                input.reason_code,
                'agent',
              );
            },
          },
          { signal: registration.signal },
        );

        setToolStatus('ready');
        addActivity('SYSTEM', 'Five WebMCP site tools registered for this page.');
      } catch (error) {
        if (!registration.signal.aborted) {
          console.error('WebMCP registration failed', error);
          setToolStatus('error');
        }
      }
    };

    void register();
    return () => registration.abort();
  }, [addActivity, stageAssignment]);

  const approveProposal = () => {
    if (!proposal) return;
    setItems((current) =>
      current.map((item) =>
        item.id === proposal.taskId
          ? { ...item, owner: proposal.worker, status: 'approved' }
          : item,
      ),
    );
    addActivity(
      'HUMAN',
      `Approved ${proposal.taskId} for ${workerFor(proposal.worker).name}.`,
    );
    setProposal(null);
  };

  const rejectProposal = () => {
    if (!proposal) return;
    setItems((current) =>
      current.map((item) =>
        item.id === proposal.taskId ? { ...item, status: 'queued' } : item,
      ),
    );
    addActivity('HUMAN', `Returned ${proposal.taskId} to the queue.`);
    setProposal(null);
  };

  const stageRecommended = () => {
    stageAssignment(
      selectedItem.id,
      selectedItem.recommended,
      selectedItem.recommended === 'deterministic'
        ? 'deterministic_fit'
        : selectedItem.recommended === 'sol'
          ? 'human_judgment'
          : selectedItem.recommended === 'luna'
            ? 'quality'
            : 'speed',
      'human',
    );
  };

  const statusLabel = {
    checking: 'CHECKING SITE TOOLS',
    ready: '5 SITE TOOLS READY',
    unavailable: 'UI READY · WEBMCP NOT DETECTED',
    error: 'SITE TOOL REGISTRATION ERROR',
  }[toolStatus];

  return (
    <main className="shell">
      <header className="topbar">
        <a className="brand" href="#top" aria-label="Captain home">
          <span className="brandMark">C</span>
          <span>
            <strong>CAPTAIN</strong>
            <small>Human-agent operations</small>
          </span>
        </a>
        <button
          className={`toolSignal ${toolStatus}`}
          type="button"
          onClick={() => setBriefingOpen((open) => !open)}
          aria-expanded={briefingOpen}
          aria-controls="agent-briefing"
        >
          <span className="pulse" />
          {statusLabel}
        </button>
      </header>

      <section className="hero" id="top">
        <div>
          <p className="eyebrow">SHARED CONTROL ROOM / SYNTHETIC DEMO</p>
          <h1>One manager. The right worker. Every decision visible.</h1>
          <p className="lede">
            Captain turns a mixed AI fleet into a legible team. The agent can
            inspect, compare, and stage work while the human keeps release
            authority.
          </p>
          <div className="heroActions">
            <button
              className="primaryButton compact"
              type="button"
              onClick={() => {
                setBriefingOpen(true);
                document
                  .getElementById('agent-briefing')
                  ?.scrollIntoView({ behavior: 'smooth', block: 'center' });
              }}
            >
              Try the agent briefing
            </button>
            <a className="textLink" href="#why-webmcp">
              Why WebMCP <span aria-hidden="true">↘</span>
            </a>
          </div>
        </div>
        <div className="heroStat" aria-label="Current mission health">
          <span>MISSION HEALTH</span>
          <strong>READY</strong>
          <small>4 checks passing · 0 private inputs</small>
          <div className="healthLine">
            <i />
            <i />
            <i />
            <i />
          </div>
        </div>
      </section>

      <section className="workspace" aria-label="Captain operations workspace">
        <article className="panel missionPanel">
          <div className="panelHead">
            <div>
              <p className="sectionLabel">MISSION 04</p>
              <h2>Prepare a verified public release</h2>
            </div>
            <span className="statusPill">IN REVIEW</span>
          </div>

          <div className="workerRail">
            {WORKERS.slice(0, 3).map((worker) => (
              <div className={`workerCard ${worker.tone}`} key={worker.id}>
                <span>{worker.name}</span>
                <strong>{worker.role}</strong>
                <small>{worker.detail}</small>
              </div>
            ))}
          </div>

          <div className="queueHead">
            <h3>Work queue</h3>
            <span>{items.filter((item) => item.status !== 'approved').length} open items</span>
          </div>
          <div className="queueList">
            {items.map((item, index) => (
              <button
                className={`queueItem ${
                  item.id === selectedTaskId ? 'selected' : ''
                }`}
                key={item.id}
                type="button"
                onClick={() => {
                  setSelectedTaskId(item.id);
                  addActivity('HUMAN', `Focused ${item.id} in the shared view.`);
                }}
                aria-pressed={item.id === selectedTaskId}
              >
                <span className="queueIndex">0{index + 1}</span>
                <span className="queueTitle">
                  <strong>{item.title}</strong>
                  <small>{item.evidence}</small>
                </span>
                <span className={`owner owner-${item.owner}`}>
                  {workerFor(item.owner).name}
                </span>
                <span className={`queueStatus ${item.status}`}>{item.status}</span>
              </button>
            ))}
          </div>
        </article>

        <aside className="panel agentPanel">
          <div className="panelHead compactHead">
            <p className="sectionLabel">SHARED INSPECTOR</p>
            <span className={`risk risk-${selectedItem.risk}`}>
              {selectedItem.risk} risk
            </span>
          </div>
          <h2>{selectedItem.id}</h2>
          <h3>{selectedItem.title}</h3>
          <p>{selectedItem.summary}</p>

          <div className="recommendation">
            <span>RECOMMENDED ROUTE</span>
            <strong>{workerFor(selectedItem.recommended).name}</strong>
            <small>{workerFor(selectedItem.recommended).detail}</small>
          </div>

          <div className="acceptanceList">
            {selectedItem.acceptance.map((criterion) => (
              <div key={criterion}>
                <span aria-hidden="true">✓</span>
                {criterion}
              </div>
            ))}
          </div>

          <button
            className="primaryButton"
            type="button"
            onClick={stageRecommended}
          >
            Stage recommended assignment
          </button>
          <small className="buttonNote">Proposal only · human approval required</small>
        </aside>
      </section>

      {proposal && (
        <section className="proposalBar" aria-live="polite">
          <div>
            <span>STAGED PROPOSAL</span>
            <strong>
              {proposal.taskId} → {workerFor(proposal.worker).name}
            </strong>
            <small>
              Source: {proposal.source} · Reason: {proposal.reasonCode.replaceAll('_', ' ')}
            </small>
          </div>
          <div className="proposalActions">
            <button type="button" className="ghostButton" onClick={rejectProposal}>
              Return
            </button>
            <button type="button" className="approveButton" onClick={approveProposal}>
              Human approve
            </button>
          </div>
        </section>
      )}

      <section
        className={`briefing panel ${briefingOpen ? 'open' : ''}`}
        id="agent-briefing"
        aria-hidden={!briefingOpen}
      >
        <div>
          <p className="sectionLabel">DEMO BRIEFING</p>
          <h2>Give the agent a goal, not a click path.</h2>
          <p>
            Open this page in ChatGPT&apos;s built-in browser and use the prompt
            below. The agent can inspect live state through the registered site
            tools, focus the same work item you see, compare routes, and stage a
            reversible proposal.
          </p>
        </div>
        <div className="promptCard">
          <span>SUGGESTED PROMPT</span>
          <p>
            Inspect the mission, compare routes for T-102, focus it in the shared
            interface, then stage the safest assignment. Do not approve or
            execute the work.
          </p>
        </div>
      </section>

      <section className="routeSection">
        <div className="sectionIntro">
          <p className="sectionLabel">ROUTE COMPARISON</p>
          <h2>The reasoning stays inspectable.</h2>
          <p>
            The page and the WebMCP tool call the same routing function. What the
            agent reads is exactly what the person sees.
          </p>
        </div>
        <div className="routeGrid">
          {selectedScores.map((score) => {
            const worker = workerFor(score.worker);
            return (
              <article className={`routeCard ${score.fit}`} key={score.worker}>
                <div>
                  <span>{worker.name}</span>
                  <b>{score.fit}</b>
                </div>
                <strong>{worker.role}</strong>
                <p>{score.rationale}</p>
                <small>
                  {worker.speed} · {worker.authority}
                </small>
              </article>
            );
          })}
        </div>
      </section>

      <section className="whySection" id="why-webmcp">
        <div className="sectionIntro">
          <p className="sectionLabel">WHY WEBMCP</p>
          <h2>Shared state beats screen guessing.</h2>
        </div>
        <div className="benefitGrid">
          <article>
            <span>01</span>
            <h3>Narrow tools</h3>
            <p>Enums and bounded schemas replace vague pointer-and-click automation.</p>
          </article>
          <article>
            <span>02</span>
            <h3>Visible changes</h3>
            <p>Agent actions update the same page the person is already reviewing.</p>
          </article>
          <article>
            <span>03</span>
            <h3>Human authority</h3>
            <p>Agents stage proposals; approval and release remain explicit human actions.</p>
          </article>
        </div>
      </section>

      <section className="activitySection panel" aria-live="polite">
        <div className="activityHead">
          <div>
            <p className="sectionLabel">RECENT ACTIVITY</p>
            <h2>Every handoff leaves a trace.</h2>
          </div>
          <span>SESSION ONLY · NO TELEMETRY</span>
        </div>
        <div className="activityList">
          {activity.map((entry) => (
            <div key={entry.id}>
              <span className={`activitySource source-${entry.source.toLowerCase()}`}>
                {entry.source}
              </span>
              <p>{entry.text}</p>
              <time>{entry.time}</time>
            </div>
          ))}
        </div>
      </section>

      <footer>
        <span>PUBLIC SYNTHETIC DATA</span>
        <span>HUMAN RELEASE GATE</span>
        <span>5 IMPERATIVE WEBMCP TOOLS</span>
        <span>WEBMCP DRAFT · 2026</span>
      </footer>
    </main>
  );
}
